// 사이드바 표시 순서 = 이 객체의 키 순서 (Nextra). 라벨 알파벳 순으로 정렬.
export default {
  "alerts": "Alerts & Notifications",
  "avatars": "Avatars",
  "badges": "Badges",
  "buttons": "Buttons",
  "charts": "Charts",
  "checkboxes": "Checkboxes",
  "date-pickers": "Date Pickers",
  "dividers": "Dividers",
  "dropdowns": "Dropdowns",
  "inputs": "Inputs",
  "link": "Link",
  "loading-indicators": "Loading Indicators",
  "modal": "Modal",
  "pagination": "Pagination",
  "progress-indicators": "Progress Indicators",
  "radio-group": "Radio Group",
  "segmented-control": "Segmented Control",
  "selects": "Selects",
  "sliders": "Sliders",
  "tab-bar": "Tab Bar",
  "table": "Table",
  "tabs": "Tabs",
  "tags": "Tags",
  "toggles": "Toggles",
  "tool-bar": "Tool Bar",
  "tooltip": "Tooltip"
}
